### ISSUE TITLE
Check is replacing has same functionality

### ISSUE THREAD

**Issue by Fabudi** [geugenm/student-bsu-by#3]
After dependencies update `backQueue` parameter of `NavController` has been set to `private`. So temporary solution is to replace `backQueue` with `currentBackStack.value`.
Check if it is correct.

**Comment by geugenm** [comment]
Settings tab is not opening at all and timetable weekdays buttons are not clickable

**Comment by Fabudi** [comment]
- In dd0465c0 settings button has been fixed.
- Timetable weekdays aren't clickable due to lack of data from server.
- Title issue closed as temporary solution is correct.
